# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testmac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testmac
	pod 'ExMj', '0.0.1'
end
